# spring.application.name=library-management
# spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/library_db}
# spring.datasource.username=${DB_USERNAME:postgres}
# spring.datasource.password=${DB_PASSWORD:postgres}
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # JWT Configurations
# secret.key=${SECRET_TOKEN:8c4d330fb8974a6c474bfe59468693ff5c16f8e677aff10cd1b129b9d910196a}
# access.token.expiration.time=${JWT_EXPIRATION:90000}
# refresh.token.expiration.time=${JWT_REFRESH_EXPIRATION:360000}

spring.application.name=library-management

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.ovnszkktcioupywlcxaw
spring.datasource.password=yguhjikhgcgvhbhjnkakn
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.devtools.restart.log-condition-evaluation-delta=false

secret.key=8c4d330fb8974a6c474bfe59468693ff5c16f8e677aff10cd1b129b9d910196a
access.token.expiration.time=90000
refresh.token.expiration.time=36000

